name: PullRequestNotifier

on:
  pull_request:
    types: [opened, edited, closed, synchronize, review_requested, ready_for_review, labeled]
    branches:
      - "**"

jobs:
  send-message-to-google-chat:
    if: always()
    uses: ionos-cloud/paas-dns-ops/.github/workflows/reusable-google-chat-action.yml@main
    secrets:
      webhook: ${{ secrets.gchat_webhook }}
